services:
  - name: rent-a-car-php
    type: web
    runtime: docker
    plan: free
    region: oregon
    buildCommand: |
      docker build -t rent-a-car-php .
    startCommand: |
      docker run -p 10000:80 rent-a-car-php
    envVars:
      - key: APP_ENV
        value: production
      - key: DATABASE_URL
        value: "mysql://freedb_Asafrushiti:fQ@DpWv9ZG7aF#2@sql.freedb.tech:3306/freedb_rent-a-car"  # Add your database URL here
